[package]
name = "mm"
version = "0.0.1"
edition = "2021"
authors = ["Mihai Miuta <miuta.mihai@gmail.com>"]
description = "CLI to handle common tasks"

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
